build:
    environment:
        php:
            version: 5.6.9
            ini:
                'date.timezone': 'Europe/Vilnius'
    tests:
        override:
            - ./bin/phpunit -c phpunit.xml
checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: false
    php_code_coverage:      false
    php_code_sniffer:
        config: { standard: 'PSR1' }
    php_changetracking: true
    php_cpd: true
    php_cs_fixer:
        config: { level: 'psr1' }
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

filter:
    paths: [ 'src/*' ]